baseURL = "https://fiverr-ebenami.netlify.app"
languageCode = "en-EN"
defaultContentLanguage = "en"
title = "Elinor Benami"
summaryLength = 30
RelativeURLs = false
CanonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
paginate = 4
paginatePath = "page"
enableGitInfo = true
pygmentsCodefences = true 
pygmentsUseClasses = true
theme = "ebenami"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  author = "Elinor Benami"
  site_name = "Ebenami"
  description = "Elinor Benami description"
  locale = "en-US"
  type = "website"

  primary_color = "#435E4D"

  # for Social Media on Header
  twitter_url = ""
  linkedin_url = ""
  github_url = ""
